### ISSUE TITLE
after auto-join channels, I need to re-join it if it needs identification

### ISSUE THREAD

**Issue by starsareintherose** [SrainApp/srain#343] opened 2021-11-15 03:36 UTC
my part of `~/.config/srain/srain.cfg`
```
server =
{
    auto-join = ["#archlinux-cn","#archlinux","#archlinux-cn-offtopic","#archlinux-offtopic","#manjaro","#endeavouros","#bioarchlinux","#c"]  # String array; Chats that are auto joined after server
                    # is created
    auto-run = []   # String array; Commands that are auto run after server
                    # is created

    user =
    {
        nickname = "kuoi"
        username = "kuoi"
        realname = ""

        login:
        {
            method = "msg-nickserv"     # String; Login method; Available values:
                                # - none: No login method, default value
                                # - nickserv: Login with NICKSERV command
                                # - msg-nickserv: Login with /msg NickServ identify
                                # - sasl-plain: Login with SASL PLAIN mechanism
                                # - sasl-ecdsa: Login with SASL
                                #   ECDSA-NIST256P-CHALLENGE mechanism

            # For method "sasl-ecdsa"
            # certificate = ""  # String; Path to login certificate file
        }

        # Default messages for performing specified action
        part-message = "Leaving."
        kick-message = "Kick."
        away-message = "Away from keyboard."
        quit-message = "El Psy Congroo."
    }
```
Then I can't join the `#archlinux` and `#archlinux-offtopic` due to passing the identification needs some time, so after I login, I need to re-join to then I can msg.
I have tried to use auto-run, it is running so quickly, though I tried to write
```
auto-run = ["/join #archlinux","/join #archlinux-offtopic"]
```
It will only report error
Also, I don't know where my msg-nickserv password is stored on my PC.

**Comment by SilverRainZ** [comment] 2021-11-17 18:44
Duplicate of #274

**Closed by SilverRainZ** 2021-11-17 18:44 UTC
Labels: duplicate
